// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxCN4YFya0K4KTLPEjFMCNBJ7Of4rViXA',
    appId: '1:995441638994:android:132b8a95f624b5ee08a98b',
    messagingSenderId: '995441638994',
    projectId: 'locationtracking-84f64',
    databaseURL: 'https://locationtracking-84f64-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationtracking-84f64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB83iWVSr2NIo11ViXBLLus6hnG7Y41WS4',
    appId: '1:995441638994:ios:4a2fb35d9ed7c47908a98b',
    messagingSenderId: '995441638994',
    projectId: 'locationtracking-84f64',
    databaseURL: 'https://locationtracking-84f64-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationtracking-84f64.appspot.com',
    iosClientId: '995441638994-2944son2atu8b67apl6srl1g47q4mqfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMapLive',
  );
}
